import { FormEvent, useEffect, useState } from 'react'
import type { UserProfile } from '../types'
import type { Shipment, TransportOrder } from '../dashboard/types'
import { customerPortalApi, driverPortalApi } from './api'
import './portal.css'
import './customer.css'

interface Props { accessToken: string; profile: UserProfile; onLogout: () => Promise<void> }
const labels: Record<string, string> = { Draft: 'Nháp', WaitingForAssignment: 'Chờ phân công', Assigned: 'Đã phân công', PickingUp: 'Đang lấy hàng', InTransit: 'Đang vận chuyển', Delivered: 'Đã giao', Completed: 'Hoàn thành', Cancelled: 'Đã hủy', DeliveryFailed: 'Giao thất bại', Planned: 'Đã lên kế hoạch', Started: 'Đang chạy', Pending: 'Chưa đến', Arrived: 'Đã đến', Skipped: 'Đã bỏ qua', Pickup: 'Lấy hàng', Delivery: 'Giao hàng' }
const formatTime = (value?: string) => value ? new Intl.DateTimeFormat('vi-VN', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : '—'

function PortalHeader({ profile, title, onLogout }: Props & { title: string }) {
  return <header className="portal-header"><div className="portal-brand"><span>TF</span><b>TRANSFLOW</b></div><div><strong>{title}</strong><small>{profile.fullName} · {profile.roles.join(', ')}</small></div><button onClick={() => void onLogout()}>Đăng xuất</button></header>
}

function Field({ name, label, type = 'text', required }: { name: string; label: string; type?: string; required?: boolean }) {
  return <label><span>{label}{required && ' *'}</span><input name={name} type={type} required={required} min={type === 'number' ? 0.01 : undefined} step={type === 'number' ? 'any' : undefined}/></label>
}

export function CustomerPortal(props: Props) {
  const [orders, setOrders] = useState<TransportOrder[]>([]), [loading, setLoading] = useState(true), [showForm, setShowForm] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const load = async () => { setLoading(true); try { setOrders(await customerPortalApi.orders(props.accessToken)); setError('') } catch (e) { setError(e instanceof Error ? e.message : 'Không thể tải đơn hàng.') } finally { setLoading(false) } }
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 30000); return () => window.clearInterval(timer) }, [props.accessToken])
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); const data = new FormData(event.currentTarget)
    try {
      await customerPortalApi.createOrder(props.accessToken, { pickupAddress: data.get('pickupAddress'), deliveryAddress: data.get('deliveryAddress'), goodsDescription: data.get('goodsDescription'), weightKg: Number(data.get('weightKg')), packageCount: Number(data.get('packageCount')), volumeM3: data.get('volumeM3') ? Number(data.get('volumeM3')) : null, expectedPickupAtUtc: data.get('expectedPickupAtUtc') ? new Date(String(data.get('expectedPickupAtUtc'))).toISOString() : null, expectedDeliveryAtUtc: data.get('expectedDeliveryAtUtc') ? new Date(String(data.get('expectedDeliveryAtUtc'))).toISOString() : null, senderName: data.get('senderName'), senderPhone: data.get('senderPhone'), recipientName: data.get('recipientName'), recipientPhone: data.get('recipientPhone'), note: data.get('note') })
      setShowForm(false); await load()
    } catch (e) { setError(e instanceof Error ? e.message : 'Không thể tạo đơn.') } finally { setBusy(false) }
  }
  async function cancel(id: string) { if (!window.confirm('Bạn chắc chắn muốn hủy đơn này?')) return; try { await customerPortalApi.cancelOrder(props.accessToken, id); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể hủy đơn.') } }
  const processing = orders.filter(x => !['Completed', 'Cancelled'].includes(x.status)).length
  const completed = orders.filter(x => x.status === 'Completed').length
  return <div className="portal-shell"><PortalHeader {...props} title="Cổng khách hàng"/><main className="portal-main"><section className="portal-hero"><div><p>QUẢN LÝ VẬN CHUYỂN</p><h1>Xin chào, {props.profile.fullName}</h1><span>Tạo yêu cầu vận chuyển và theo dõi trạng thái xử lý.</span></div><button className="portal-primary" onClick={() => setShowForm(!showForm)}>{showForm ? 'Đóng' : '+ Tạo đơn mới'}</button></section><section className="customer-stats"><div><small>TỔNG ĐƠN</small><b>{orders.length}</b><span>Tất cả yêu cầu vận chuyển</span></div><div><small>ĐANG XỬ LÝ</small><b>{processing}</b><span>Đơn đang trên hành trình</span></div><div><small>HOÀN THÀNH</small><b>{completed}</b><span>Đơn đã giao thành công</span></div></section>{error && <div className="portal-error">{error}</div>}{showForm && <form className="portal-form" onSubmit={submit}><h2>Tạo yêu cầu vận chuyển</h2><div className="portal-grid"><Field name="pickupAddress" label="Địa chỉ lấy hàng" required/><Field name="deliveryAddress" label="Địa chỉ giao hàng" required/><Field name="senderName" label="Người gửi"/><Field name="senderPhone" label="SĐT người gửi"/><Field name="recipientName" label="Người nhận"/><Field name="recipientPhone" label="SĐT người nhận"/><Field name="goodsDescription" label="Mô tả hàng hóa" required/><Field name="weightKg" label="Khối lượng (kg)" type="number" required/><Field name="packageCount" label="Số kiện" type="number" required/><Field name="volumeM3" label="Thể tích (m³)" type="number"/><Field name="expectedPickupAtUtc" label="Thời gian lấy dự kiến" type="datetime-local"/><Field name="expectedDeliveryAtUtc" label="Thời gian giao dự kiến" type="datetime-local"/><Field name="note" label="Ghi chú"/></div><button className="portal-primary" disabled={busy}>{busy ? 'Đang gửi...' : 'Gửi yêu cầu'}</button></form>}<h2 className="portal-section-title">Đơn vận chuyển gần đây</h2><section className="portal-list">{loading ? <p>Đang tải...</p> : orders.length === 0 ? <div className="portal-empty">Bạn chưa có đơn vận chuyển nào.</div> : orders.map(x => <article className="order-card" key={x.id}><div className="portal-card-top"><b>{x.code}</b><span className={`portal-status status-${x.status.toLowerCase()}`}>{labels[x.status] || x.status}</span></div><div className="portal-route"><div><small>ĐIỂM LẤY</small><strong>{x.pickupAddress}</strong></div><i>→</i><div><small>ĐIỂM GIAO</small><strong>{x.deliveryAddress}</strong></div></div><OrderProgress status={x.status}/><div className="portal-meta"><span>{x.goodsDescription}</span><span>{x.weightKg.toLocaleString('vi-VN')} kg · {x.packageCount} kiện</span><span>Giao dự kiến: {formatTime(x.expectedDeliveryAtUtc)}</span></div>{['Draft','WaitingForAssignment'].includes(x.status) && <button className="portal-danger" onClick={() => void cancel(x.id)}>Hủy đơn</button>}</article>)}</section></main></div>
}

function OrderProgress({ status }: { status: string }) {
  const steps = ['WaitingForAssignment', 'Assigned', 'InTransit', 'Completed']
  const aliases: Record<string, number> = { Draft: 0, PickingUp: 2, Delivered: 3, DeliveryFailed: 2, Cancelled: -1 }
  const current = aliases[status] ?? steps.indexOf(status)
  return <div className={`order-progress ${status === 'Cancelled' ? 'cancelled' : ''}`}>{steps.map((step, index) => <div className={index <= current ? 'done' : ''} key={step}><i>{index < current ? '✓' : index + 1}</i><span>{['Tiếp nhận', 'Phân công', 'Vận chuyển', 'Hoàn thành'][index]}</span></div>)}</div>
}

export function DriverPortal(props: Props) {
  const [shipments, setShipments] = useState<Shipment[]>([]), [error, setError] = useState(''), [busy, setBusy] = useState('')
  const load = async () => { try { setShipments(await driverPortalApi.shipments(props.accessToken)); setError('') } catch (e) { setError(e instanceof Error ? e.message : 'Không thể tải chuyến xe.') } }
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 30000); return () => window.clearInterval(timer) }, [props.accessToken])
  const position = () => new Promise<GeolocationPosition>((resolve, reject) => navigator.geolocation.getCurrentPosition(resolve, reject, { enableHighAccuracy: true, timeout: 15000 }))
  async function shipmentAction(id: string, action: 'start' | 'complete') { setBusy(id + action); try { await driverPortalApi.shipmentAction(props.accessToken, id, action); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Thao tác thất bại.') } finally { setBusy('') } }
  async function sendLocation(id: string) { setBusy(id + 'gps'); try { const p = await position(); await driverPortalApi.location(props.accessToken, id, { latitude: p.coords.latitude, longitude: p.coords.longitude, speedKph: p.coords.speed == null ? null : p.coords.speed * 3.6, accuracyMeters: p.coords.accuracy }); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Không lấy được GPS. Hãy cấp quyền vị trí.') } finally { setBusy('') } }
  async function stopAction(stopId: string, action: 'arrive' | 'complete' | 'skip', delivery: boolean) { setBusy(stopId + action); try { if (action === 'arrive') { const p = await position(); await driverPortalApi.arrive(props.accessToken, stopId, { latitude: p.coords.latitude, longitude: p.coords.longitude }) } else if (action === 'skip') await driverPortalApi.skipStop(props.accessToken, stopId); else { let proof: unknown; if (delivery) { const receiverName = window.prompt('Tên người nhận hàng:'); if (!receiverName) return; const photoUrl = window.prompt('URL ảnh giao hàng (hoặc để trống để nhập xác nhận):') || null; const signatureData = photoUrl ? null : window.prompt('Nhập xác nhận/chữ ký người nhận:'); proof = { receiverName, photoUrl, signatureData, note: null } } await driverPortalApi.completeStop(props.accessToken, stopId, proof) } await load() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể cập nhật điểm dừng.') } finally { setBusy('') } }
  return <div className="portal-shell"><PortalHeader {...props} title="Cổng tài xế"/><main className="portal-main"><section className="portal-hero"><div><p>NHIỆM VỤ HÔM NAY</p><h1>Chuyến xe của tôi</h1><span>Bắt đầu chuyến, cập nhật GPS và xác nhận từng điểm giao nhận.</span></div></section>{error && <div className="portal-error">{error}</div>}<section className="portal-list">{shipments.length === 0 ? <div className="portal-empty">Tài khoản chưa được liên kết tài xế hoặc chưa có chuyến xe.</div> : shipments.map(x => <article className="shipment-card" key={x.id}><div className="portal-card-top"><div><b>{x.code}</b><small>{x.licensePlate} · {x.driverName}</small></div><span className={`portal-status status-${x.status.toLowerCase()}`}>{labels[x.status] || x.status}</span></div><div className="shipment-summary"><span>Khởi hành <b>{formatTime(x.plannedDepartureAtUtc)}</b></span><span>Đơn hàng <b>{x.orders.length}</b></span><span>Điểm dừng <b>{x.routeStops.length}</b></span></div>{x.latestLocation && <a className="map-link" target="_blank" rel="noreferrer" href={`https://www.openstreetmap.org/?mlat=${x.latestLocation.latitude}&mlon=${x.latestLocation.longitude}`}>Vị trí gần nhất: {x.latestLocation.latitude.toFixed(5)}, {x.latestLocation.longitude.toFixed(5)} ↗</a>}<div className="shipment-actions">{x.status === 'Assigned' && <button onClick={() => void shipmentAction(x.id, 'start')} disabled={!!busy}>Bắt đầu chuyến</button>}{x.status === 'Started' && <button onClick={() => void sendLocation(x.id)} disabled={!!busy}>Cập nhật GPS</button>}{x.status === 'Started' && <button onClick={() => void shipmentAction(x.id, 'complete')} disabled={!!busy}>Hoàn thành chuyến</button>}</div><div className="stop-list">{x.routeStops.map(stop => <div className="stop-item" key={stop.id}><span className="stop-number">{stop.sequence}</span><div><small>{labels[stop.type]} · {labels[stop.status]}</small><b>{stop.address}</b>{stop.arrivedAtUtc && <em>Đến lúc {formatTime(stop.arrivedAtUtc)}</em>}</div><div>{stop.status === 'Pending' && x.status === 'Started' && <button onClick={() => void stopAction(stop.id, 'arrive', stop.type === 'Delivery')}>Đã đến</button>}{stop.status === 'Arrived' && <><button onClick={() => void stopAction(stop.id, 'complete', stop.type === 'Delivery')}>Hoàn tất</button><button className="muted" onClick={() => void stopAction(stop.id, 'skip', stop.type === 'Delivery')}>Bỏ qua</button></>}</div></div>)}</div></article>)}</section></main></div>
}
